# Generated by Django 5.0.4 on 2024-08-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscriber_subscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='partners',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='partners_image',
            field=models.ImageField(blank=True, null=True, upload_to='partners_images/'),
        ),
    ]
